version: '3'

services:
  backend:
    image: motion-backend:latest
    ports:
      - 8000:8000
    env_file:
      - ./env/dev.env
    volumes:
      - ./backend:/backend
    command: "python manage.py runserver 0:8000"
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    env_file:
      - ./env/dev.env
    ports:
      - 5433:5432
    volumes:
      - postgres_docker_volume:/var/lib/postgresql/data

volumes:
  postgres_docker_volume:
