name: backend_motion

dependencies:
  - python=3.6
  - psycopg2
  - pip:
    - Django==2.2.2
    - flake8
    - djangorestframework==3.9.4
    - markdown==3.1.1
    - django-filter==2.1.0
    - djangorestframework_simplejwt==4.3.0
    - coreapi==2.3.3
    - Pygments==2.4.2
    - gunicorn
    - Pillow

