name: backend_motion

dependencies:
  - python=3.9.7
  - psycopg2=2.8.5
  - pip==21.2.4
  - pip:
      - django==3.2.7
      - djangorestframework==3.12.4
      - PyJWT==2.1.0
      - djangorestframework-simplejwt==4.8.0
      - drf-yasg==1.20.0
      - pillow==8.3.2
      - gunicorn==20.1.0
      - flake8==3.9.2
