# Generated by Django 3.2.7 on 2021-10-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='title')),
                ('content', models.TextField(max_length=300, verbose_name='content')),
                ('images', models.ImageField(blank=True, null=True, upload_to='post_media', verbose_name='images')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('shared', models.IntegerField(blank=True, null=True, verbose_name='shared')),
            ],
        ),
    ]
