# Generated by Django 3.2.7 on 2021-10-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_user'),
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='commented_posts', to='comment.Comment', verbose_name='comments'),
        ),
    ]
