# Generated by Django 3.2.7 on 2021-10-13 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_friend_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friend_request',
            field=models.ManyToManyField(blank=True, related_name='requested_from', to=settings.AUTH_USER_MODEL, verbose_name='friends_request'),
        ),
    ]
