# Generated by Django 3.2.7 on 2021-10-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
