# Generated by Django 3.2.7 on 2021-10-13 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends_with',
            field=models.ManyToManyField(blank=True, related_name='friends_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
